#pragma once

#include "NativeGameplayTags.h"

namespace D1GameplayTags
{
	// InitState
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_Spawned);
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_DataAvailable);
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_DataInitialized);
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_GameplayReady);

	// Input
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look_Mouse);
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look_Stick);
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Crouch);
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Attack_MainHand);
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Attack_OffHand);
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_ChangeEquip_Primary);
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_ChangeEquip_Secondary);
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_ChangeEquip_Tertiary);
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_ChangeEquip_Quaternary);
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Widget_OpenInventory);
	
	// Ability
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_IsDead);
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_Cooldown);
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_Cost);
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_TagsBlocked);
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_TagsMissing);
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_Networking);
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_ActivationGroup);
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Behavior_SurvivesDeath);

	D1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Attack);
	D1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Attack_1);
	D1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Attack_2);
	D1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Attack_3);
	D1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Attack_Bow);
	D1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Block);
	D1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ChangeEquip);
	D1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ADS);

	// Status
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Crouching);
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_AutoRunning);
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Death);
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Death_Dying);
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Death_Dead);
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Attack);
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Block);
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_ChangeEquip);
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_ADS);
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Succeeded);
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Failed);

	// Gameplay Event
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Death);
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Reset);
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_RequestReset);
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Montage_Begin);
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Montage_Tick);
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Montage_End);
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Trace);
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_ChangeEquip);
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_ArrowVisibility);

	// SetByCaller
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_Damage);
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_Heal);
	
	// Cheat
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cheat_GodMode);
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cheat_UnlimitedHealth);
	
	// Movement
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Walking);
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_NavWalking);
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Falling);
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Swimming);
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Flying);
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Custom);

	// Message
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Message_Item_WeaponEquipStateChanged);
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Message_Item_EquipmentEntryChanged);
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Message_Item_InventoryEntryChanged);
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Message_Notification);

	// Attribute
	D1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Primary_Health);
	D1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Primary_MaxHealth);
	D1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Primary_Stamina);
	D1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Primary_MaxStamina);
	D1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Primary_MoveSpeed);
	D1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Primary_MoveSpeedPercent);
	D1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Primary_BaseDamage);
	D1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Primary_BaseDefense);

	// GameplayCue
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Impact_Weapon);
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_HitReact);

	// Cooldown
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Bow_Fire);
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Jump);

	// GamePhase
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GamePhase_WaitForPlayers);
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GamePhase_Betting);
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GamePhase_Battle);

	// HUD
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(HUD_Slot_MyInventory);
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(HUD_Slot_OtherInventory);
	
	D1GAME_API	extern const TMap<uint8, FGameplayTag> MovementModeTagMap;
	D1GAME_API	extern const TMap<uint8, FGameplayTag> CustomMovementModeTagMap;
	
	D1GAME_API	FGameplayTag FindTagByString(const FString& TagString, bool bMatchPartialString = false);
};
