#pragma once

#include "NativeGameplayTags.h"

namespace D1GameplayTags
{
	// InitState
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_Spawned);
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_DataAvailable);
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_DataInitialized);
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_GameplayReady);

	// Input
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look_Mouse);
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look_Stick);
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Jump);
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Dash);
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Crouch);
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Interact);
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_ChangeEquip_Primary);
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_ChangeEquip_Secondary);
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_ChangeEquip_Tertiary);
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_ChangeEquip_Quaternary);
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Ability_Confirm);
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Ability_Cancel);
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Attack_MainHand);
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Attack_OffHand);
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Widget_Inventory);
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Widget_WorldMap);
	
	// Ability
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_IsDead);
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_Cooldown);
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_Cost);
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_TagsBlocked);
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_TagsMissing);
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_Networking);
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_ActivationGroup);
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Behavior_SurvivesDeath);

	D1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Death);
	D1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Jump);
	D1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Dash_Check);
	D1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Dash_Active);
	D1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ChangeEquip);
	D1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Attack);
	D1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Attack_1);
	D1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Attack_2);
	D1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Attack_3);
	D1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Attack_Bow);
	D1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Throw);
	D1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Block);
	D1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ADS);
	D1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Interact);
	D1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Interact_Active);
	D1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Interact_Object);
	D1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Widget_Inventory);
	D1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Widget_WorldMap);
	D1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_HitReact);

	// Status
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Crouch);
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Jump);
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Death);
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Death_Dying);
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Death_Dead);
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Attack);
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Throw);
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Block);
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_ChangeEquip);
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_ADS);
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Dash);
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Succeeded);
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Failed);
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Interact);
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_HitReact);

	// Gameplay Event
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Death);
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Montage_Begin);
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Montage_Tick);
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Montage_End);
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Trace);
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_ChangeEquip);
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_ArrowVisibility);
	
	// Cheat
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cheat_GodMode);
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cheat_UnlimitedHealth);
	
	// Movement
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Walking);
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_NavWalking);
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Falling);
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Swimming);
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Flying);
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Custom);

	// Message
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Message_Notification);
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Message_Interaction_Notice);
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Message_Interaction_Progress);
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Message_Initialize_MyInventory);
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Message_Initialize_OtherInventory);
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Message_Initialize_MyEquipment);
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Message_Initialize_OtherEquipment);

	// SetByCaller
	D1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_IncomingHeal);
	D1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_IncomingDamage);
	D1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_PhysicalWeaponDamage);
	D1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_MoveSpeed);
	D1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_Strength);
	D1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_Defense);
	D1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_Vigor);
	D1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_Agility);
	D1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_Resourcefulness);

	// GameplayCue
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Impact_Weapon);
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_HitReact);
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Statue_Loop);
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Statue_Success);
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Statue_Fail);

	// Cooldown
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Bow_Fire);
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Jump);
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Dash);
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Statue);

	// GamePhase
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GamePhase_WaitForPlayers);

	// HUD
	D1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(HUD_Slot_Reticle);
	
	D1GAME_API	extern const TMap<uint8, FGameplayTag> MovementModeTagMap;
	D1GAME_API	extern const TMap<uint8, FGameplayTag> CustomMovementModeTagMap;
	
	D1GAME_API	FGameplayTag FindTagByString(const FString& TagString, bool bMatchPartialString = false);
};
