#pragma once

#include "NativeGameplayTags.h"

namespace D1GameplayTags
{
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Dead);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_DamageImmunity);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_InputBlocked);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Jump);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Attack);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Interact);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_EquipWeapon);
	
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Interact);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Attack_Begin);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Attack_Tick);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Attack_End);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_EquipWeapon_Primary);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_EquipWeapon_Secondary);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_EquipWeapon_CycleBackward);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_EquipWeapon_CycleForward);
	
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Action_Move);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Action_Look);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Action_Crouch);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Action_Jump);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Action_Inventory);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Action_Interact);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Action_Attack_MainHand);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Action_Attack_OffHand);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Action_EquipWeapon_Primary);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Action_EquipWeapon_Secondary);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Action_EquipWeapon_CycleBackward);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Action_EquipWeapon_CycleForward);

	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Death);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Jump);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Interact);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Attack);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_EquipWeapon);

	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Primary_Health);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Primary_MaxHealth);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Primary_Mana);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Primary_MaxMana);
	
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Primary_AttackSpeed);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Primary_MoveSpeed);
	
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Primary_BaseDamage);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Primary_BaseDefense);
	
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Secondary_Strength);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Secondary_Will);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Secondary_Vigor);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Secondary_Agility);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Secondary_Knowledge);
	
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attack_Physical);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attack_Magical);
}
